name: Run Earthquake PH weekly

on:
  schedule:
    - cron: '0 11 * * *'  # Every day at 11:00 AM UTC (7:00 PM PHT)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Practical/Projects/PH Earthquakes/requirements.txt"

      - name: Run Earthquake PH scraper
        run: python "Practical/Projects/PH Earthquakes/Earthquake_PH_Web_Scraping.py"

      - name: Extract output filename from metadata.json
        id: meta
        run: |
          OUTPUT_FILE=$(jq -r '.output_file' "Practical/Projects/PH Earthquakes/metadata.json")
          echo "output_file=$OUTPUT_FILE" >> $GITHUB_OUTPUT

      - name: Commit and push updated CSV and metadata
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add "Practical/Projects/PH Earthquakes/metadata.json"
          git add "Practical/Projects/PH Earthquakes/${{ steps.meta.outputs.output_file }}"
          git commit -m "Update earthquake CSV and metadata.json using script"
          git push || echo "No changes to commit"
